name: Publish

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Load cached docker layers
        uses: actions/cache@v4.0.2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build publish_vite_plugin_vue_examples docker image
        run: |
          docker buildx build \
          --cache-from type=local,src=/tmp/.buildx-cache \
          --cache-to type=local,dest=/tmp/.buildx-cache-new,mode=max \
          --tag publish_vite_plugin_vue_examples \
          --load \
          .
#      - name: Publish vite_plugin_vue_examples
#        run: |
#          docker run -e NPM_AUTH_TOKEN="${{ secrets.NPM_AUTH_TOKEN }}" publish_vite_plugin_vue_examples
      - name: Tag published version
        run: |
          package_json=$(cat package.json)
          echo "${{fromJson(package_json).version}}"
      - name: Prevent consistently growing buildx cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache