name: Verify Source

on:
  push:
    branches:
      - main

jobs:
  verify:
    name:  Verify Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Build Docker image - stage verify
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          target: verify
          cache-from: type=local,src=/buildx-cache
          cache-to: type=local,dest=/buildx-cache-new
      - name: Prevent consistently growing buildx cache
        run:
          rm -rf /buildx-cache
          mv /buildx-cache-new /buildx-cache